CREATE TABLE biz_audit_log (
  id                BIGINT       NOT NULL AUTO_INCREMENT COMMENT '主键',
  trace_id          VARCHAR(64)  NOT NULL COMMENT '链路ID',
  request_id        VARCHAR(64)  NULL COMMENT '请求ID(可选)',
  biz_type          VARCHAR(64)  NOT NULL COMMENT '业务类型(模块/对象)',
  biz_name          VARCHAR(128) NULL COMMENT '业务名称(中文)',
  biz_id            VARCHAR(64)  NULL COMMENT '业务主键/单号',
  biz_key           VARCHAR(128) NULL COMMENT '业务扩展Key(可选)',
  op_type           VARCHAR(16)  NOT NULL COMMENT '操作类型:CREATE/UPDATE/DELETE/APPROVE/REJECT/IMPORT/EXPORT/BATCH',
  result_status     VARCHAR(16)  NOT NULL DEFAULT 'SUCCESS' COMMENT '结果状态:SUCCESS/FAIL/PARTIAL',
  success           TINYINT      NOT NULL DEFAULT 1 COMMENT '是否成功(1/0)',
  error_code        VARCHAR(64)  NULL COMMENT '错误码(可选)',
  error_msg         VARCHAR(2000) NULL COMMENT '错误信息(截断保存)',
  batch_flag        TINYINT      NOT NULL DEFAULT 0 COMMENT '是否批量',
  batch_count       INT          NULL COMMENT '批量数量',
  class_name        VARCHAR(255) NULL COMMENT '目标类名',
  method_name       VARCHAR(255) NULL COMMENT '目标方法名',
  method            VARCHAR(500) NULL COMMENT 'Java方法签名',
  request_uri       VARCHAR(255) NULL COMMENT '请求URI',
  request_method    VARCHAR(16)  NULL COMMENT 'HTTP方法',
  request_params    LONGTEXT     NULL COMMENT '请求参数(可选/脱敏后)',
  duration_ms       BIGINT       NULL COMMENT '耗时毫秒',
  oper_user_id      BIGINT       NULL COMMENT '操作人ID',
  oper_user_name    VARCHAR(64)  NULL COMMENT '操作人账号',
  oper_nick_name    VARCHAR(64)  NULL COMMENT '操作人姓名',
  oper_dept_id      BIGINT       NULL COMMENT '部门ID',
  oper_dept_name    VARCHAR(128) NULL COMMENT '部门名称',
  oper_ip           VARCHAR(64)  NULL COMMENT 'IP',
  oper_location     VARCHAR(255) NULL COMMENT 'IP归属地',
  oper_browser      VARCHAR(128) NULL COMMENT '浏览器',
  oper_os           VARCHAR(128) NULL COMMENT '操作系统',
  before_json       LONGTEXT     NULL COMMENT '变更前JSON(删除前必存)',
  after_json        LONGTEXT     NULL COMMENT '变更后JSON',
  diff_json         LONGTEXT     NULL COMMENT '差异JSON(结构化)',
  extra_json        LONGTEXT     NULL COMMENT '扩展信息(如导入结果统计)',
  create_time       DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (id),
  KEY idx_create_time (create_time),
  KEY idx_biz (biz_type, biz_id),
  KEY idx_user_time (oper_user_id, create_time),
  KEY idx_optype_time (op_type, create_time),
  KEY idx_success_time (success, create_time),
  KEY idx_trace_id (trace_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='高级版业务审计日志(主表)';

CREATE TABLE biz_audit_log_detail (
  id             BIGINT       NOT NULL AUTO_INCREMENT COMMENT '主键',
  log_id         BIGINT       NOT NULL COMMENT '主表ID',
  item_path      VARCHAR(255) NULL COMMENT '明细路径, 如items/detailList',
  item_key       VARCHAR(128) NULL COMMENT '明细对齐键, 如id=101',
  item_biz_id    VARCHAR(64)  NULL COMMENT '明细项业务ID',
  item_name      VARCHAR(128) NULL COMMENT '明细项名称(可选)',
  seq_no         INT          NULL COMMENT '序号(可选)',
  change_type    VARCHAR(16)  NULL COMMENT '变更类型:ADDED/REMOVED/MODIFIED/UNCHANGED/FAILED',
  before_json    LONGTEXT     NULL COMMENT '明细变更前JSON',
  after_json     LONGTEXT     NULL COMMENT '明细变更后JSON',
  diff_json      LONGTEXT     NULL COMMENT '明细差异JSON',
  success        TINYINT      NOT NULL DEFAULT 1 COMMENT '该明细项是否成功(批量导入常用)',
  error_msg      VARCHAR(2000) NULL COMMENT '该明细项错误信息',
  create_time    DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (id),
  KEY idx_log_id (log_id),
  KEY idx_item_biz_id (item_biz_id),
  KEY idx_create_time (create_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='高级版业务审计日志(明细表)';
